### PR TITLE
Feature#96 manage clients

### PR DESCRIPTION
**Pull request by HikingCarrot7**
# Description
What did you implement/Why did you implement this:
 - Added client model, controller & relationship with the business model.
 - Added simple styling for index, new & edit views for clients.
 - Added functionality to attach a client to a new sale.
  
  ## Screenshots
### Index view for clients.
index_clients

### New client view.
new_client

### CODE REVIEW

**Review by acorzo — APPROVED** [review]
LGTM, Any other files missing? 🤣

**Review by juperameza — APPROVED** [review]
LGTM! But try to keep the commits and changes relevant to the pr description

**Review by juperameza — APPROVED** [review]

**Review by AgustinPalmaM — APPROVED** [review]
LGTM

**Review by ruruisu — APPROVED** [review]
LGTM

**Pull request merged**
