### PR TITLE
Added many to many relationship between products and sales

### PR DESCRIPTION
**Pull request by HikingCarrot7**
# Description
What did you implement/Why did you implement this:
 - Added Sale entity.
 - Created many-to-many relationship between products and sales through the ProductSale entity.

### CODE REVIEW

**Review by YilKanda — APPROVED** [review]
LGTM!

**Review by acorzo — DISMISSED** [review]
Good job 👍

**Review by JuanequeX — DISMISSED** [review]
LGTM

**Review by YilKanda — APPROVED** [review]

**Review by Jumaquba — APPROVED** [review]
excellent

**Pull request merged**
