### PR TITLE
Feature#26 allow user to view and edit his info

### PR DESCRIPTION
**Pull request by HikingCarrot7**
# Description
What did you implemented/Why did you implemented this:
 - Implemented functionality to update user info.
 - Only update the password if the user provides one.
  
  ## Screenshots 

edit_user

### CODE REVIEW

**Review by AgustinPalmaM — APPROVED** [review]
lgtm

**Review by YilKanda — DISMISSED** [review]
LGTM!

**Review by EdwardMD — APPROVED** [review]
LGTM!

**Review by acorzo — APPROVED** [review]
Good job 👍

**Pull request merged**
