### PR TITLE
Added name field as required when sign up

### PR DESCRIPTION
**Pull request by HikingCarrot7**
# Description
- Implemented the functionality to permit a user to sign up with a SAPEC account using his name, email, and password

### CODE REVIEW

**Review by EdwardMD — APPROVED** [review]
LGMT!

**Review by V-Juarez — APPROVED** [review]

**Review by JuanequeX — APPROVED** [review]
LGTM

**Review by acorzo — APPROVED** [review]
LGTM 👍

**Review by Jumaquba — APPROVED** [review]

**Review by AgustinPalmaM — APPROVED** [review]
lgtm

**Pull request merged**
